# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: nuke

before:
  hooks:
    - go mod tidy

builds:
  - id: nuke
    main: ./main.go
    binary: "nuke-{{ .Os }}-{{ .Arch }}"
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: binary
    name_template: "{{ .Binary }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# Release configuration
release:
  github:
    owner: amantham20
    name: nuke_rm
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  footer: |
    ## Installation

    ### macOS (Apple Silicon)
    ```bash
    curl -L https://github.com/amantham20/nuke_rm/releases/latest/download/nuke-darwin-arm64 -o nuke
    chmod +x nuke
    sudo mv nuke /usr/local/bin/
    ```

    ### macOS (Intel)
    ```bash
    curl -L https://github.com/amantham20/nuke_rm/releases/latest/download/nuke-darwin-amd64 -o nuke
    chmod +x nuke
    sudo mv nuke /usr/local/bin/
    ```

    ### Linux (x86_64)
    ```bash
    curl -L https://github.com/amantham20/nuke_rm/releases/latest/download/nuke-linux-amd64 -o nuke
    chmod +x nuke
    sudo mv nuke /usr/local/bin/
    ```

    ### Linux (ARM64)
    ```bash
    curl -L https://github.com/amantham20/nuke_rm/releases/latest/download/nuke-linux-arm64 -o nuke
    chmod +x nuke
    sudo mv nuke /usr/local/bin/
    ```

    ### From Source
    ```bash
    git clone https://github.com/amantham20/nuke_rm.git
    cd nuke_rm
    go build -o nuke .
    sudo mv nuke /usr/local/bin/
    ```
